Description: >
  UdaPeople frontend stack.
Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "udapeople-kwcipmu1qc"
      AccessControl: PublicRead

      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  

Outputs:

  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Description: URL for website hosted on S3
